# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
  branches:
    include:
      - master

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

pool: 
  name: SelfHostedPool
  #vmImage: 'windows-latest' 
  demands:
    - Agent.Name -equals TIGER      


jobs:

  - job: BuildConsoleApp

    steps:

    - script: |
        echo 'Pipeline.Workspace=$(Pipeline.Workspace)'
        echo 'Build.ArtifactStagingDirectory=$(Build.ArtifactStagingDirectory)'
        echo 'Build.StagingDirectory=$(Build.StagingDirectory)'
        echo 'Pipeline.Workspace=$(Pipeline.Workspace)'
        echo 'Build.BinariesDirectory=$(Build.BinariesDirectory)'
        echo 'Build.SourcesDirectory=$(Build.SourcesDirectory)'
        echo 'Build.BinariesDirectory=$(Build.BinariesDirectory)'
        echo 'Agent.BuildDirectory=$(Agent.BuildDirectory)'
      displayName: 'Show Env'

    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)\bin\Release'
        Contents: '**\*.exe'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
        CleanTargetFolder: true
        OverWrite: true

    - script: ren *.exe TestAzureDevOpsConsoleApp_$(Build.BuildNumber).exe
      workingDirectory: $(Build.ArtifactStagingDirectory)
      displayName: Rename Artifact

    - script: dir
      workingDirectory: $(Build.ArtifactStagingDirectory)
      displayName: List Artifact Dir


    - task: VSTest@2
      inputs:
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - task: PublishBuildArtifacts@1
      inputs:
        # D:\a\1\s\bin\Release\TestAzureDevOpsConsoleApp.exe
        # 
        #PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
